image: docker:18


variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"  
  CI_DEBUG_TRACE: "true"

before_script:
  # - export GRADLE_USER_HOME=`pwd`/.gradle
  #- export JAVA_HOME=/opt/java/openjdk

services:
  - docker:stable-dind

stages:
  - build_and_docker_multistage  
  - acceptance


#build:
#  stage: build
#  script:    
#    - ./gradlew clean build 
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle
#  artifacts:
#    paths:
#      - car-pooling-challenge-dnevado/build/

docker:
  stage: build_and_docker_multistage
  script:
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:latest  .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:latest
    
## Uncomment the acceptance step and do not remove or edit, this step is
## required for us to accept your submission!
acceptance:
   image: cabify/challenge:latest
   stage: acceptance
   only: 
     - master
   dependencies: []
   services:
     - name: ${CI_REGISTRY_IMAGE}:latest
       alias: pooling
   script:
     - /harness --address http://pooling:9091 acceptance