version: 0.2

# phases: 
#    install:
#        runtime-versions:
#            nodejs: 10
#        commands:
#            - echo "installing something"
#    pre_build:
#        commands: 
#            - echo "we are in the pre build phase"
#    build:
#        commands:
#            - echo "we are in the build block"
#             - echo "we will run some tests"
#             - grep -Fq "Congratulations" index.html
#     post_build:
#         commands:
#             - echo "we are in the post build phase"
            
phases:
  install:
    runtime-versions:
      java: corretto11      
    commands: 
  build:
    commands:
      - ./gradlew build
      #- yum update -y
      #- yum install -y software-properties-common
      #- add-apt-repository ppa:openjdk-r/ppa
      #- yum update -y
      #- amazon-linux-extras install java-openjdk11 
      #- yum install -y gradle